### ISSUE TITLE
What if score is null? 

### ISSUE THREAD

**Issue by vpapiez** [oreqizer/pa165-yellow-yak#26]
What if score is null? How can this situation happen and how to test it? 
ScoreFacadeImpl.create(Long competitionId, Long playerId) {
Score score = scoreService.create(competitionId, playerId);
 return beanMappingService.mapTo(score, ScoreDTO.class);

**Comment by MatejHor** [comment]
We secure that beanMappingService.mapTo can get null object and return null object
