### ISSUE TITLE
NPE and uncovered test

### ISSUE THREAD

**Issue by vpapiez** [oreqizer/pa165-yellow-yak#8]
Missing test and uncovered NPE.

when I write this. 
@Test
    public void RemoveNullTest(){

        Competitor comp = null;
        competitorDao.remove(comp);
    }
I have NPE in competitorDAO method.

**Comment by MatejHor** [comment]
We don't want to handle exceptions in DaoImpl, we will do it in the upper layer (services). We will implement a unit test that will test to throw an exception when DAO remove method got null.
